# This Dockerfile is to build Pytorch master with oneCLL and Torch CCL. Change BASE_IMG for any other base image

# Select the base 
ARG BASE_IMG=pt_u18:master
FROM $BASE_IMG

# clone and install oneCCL
RUN git clone https://github.com/oneapi-src/oneCCL.git && \
    cd oneCCL && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j && make install &&  cd .. && rm -rf oneCCL

# clone and install torch CCL
RUN git clone https://github.com/intel/torch-ccl.git && \
    . /usr/local/env/setvars.sh && cd torch-ccl && \
    sed -i "s/record_function.h/record_function_ops.h/g" ./src/ProcessGroupCCL.cpp && \
    python setup.py install && cd .. && rm -rf torch-ccl

# activate oneCCL
RUN echo "source /usr/local/env/setvars.sh" > ~/.bashrc
