# This Dockerfile is to build Pytorch with Intel optimization.

# use Ubuntu 18 as base
FROM ubuntu:18.04

# Install ubuntu packages
RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        git \
        curl \
        wget \
        numactl \
        ca-certificates \
        libjpeg-dev \
        libpng-dev && \
        rm -rf /var/lib/apt/lists/*

# install and setup conda 
ENV PATH /opt/conda/bin:$PATH
RUN curl -fsSL -v -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm -rf ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=3.7 conda-build pyyaml numpy \
    autoconf ninja  mkl mkl-include setuptools cmake cffi && \
    /opt/conda/bin/conda clean -ya

# Environmemt settings for python install
ENV CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
ENV USE_CUDA=0
ENV USE_CUDNN=0

# clone and install pytorch
RUN git clone --recursive https://github.com/pytorch/pytorch && \
    cd pytorch && \
    python3 setup.py clean && python3 setup.py install && \
    python3 setup.py clean && rm -rf pytorch

# install Jemalloc
WORKDIR /tmp
RUN git clone https://github.com/jemalloc/jemalloc.git && \
    cd /tmp/jemalloc && ./autogen.sh --prefix=/usr/local --enable-prof && \
    make && make install && \
    rm -rf /tmp/jemalloc

# enable Jemalloc
ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so
ENV MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:9000000000,muzzy_decay_ms:9000000000"
