# select the base image 
ARG BASE_IMG=pt_u18:master
FROM $BASE_IMG

RUN git clone https://github.com/huggingface/transformers.git && \
    cd transformers && pip install . && cd .. && rm -rf transformers
RUN pip install tensorboardX
